import "dotenv/config";

export const {
  SERVER_PORT,
  SERVER_HOST,
  DB_HOST,
  DB_USER,
  DB_PASSWORD,
  DB_NAME,
  DB_PORT,
  DATABASE_URL,
  CORS_URL,
  // GOOGLE_CLIENT_ID,
  // GOOGLE_CLIENT_SECRET,
  GOOGLE_CALLBACK_URL,
  JWT_PRIVATE_KEY ,
  JWT_ACCESS_EXPIRATION_TIME,
  JWT_REFRESH_EXPIRATION_TIME,
  EMAIL_USER,
  EMAIL_PASS,
  FRONTEND_URL,
} = process.env;

